# Generated by Django 5.0.6 on 2025-07-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='courses/')),
                ('duration', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite'), ('Online/Onsite', 'Online/Onsite')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('father_phone', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, choices=[('Master', 'Master'), ('Bachelor', 'Bachelor'), ('Intermediate', 'Intermediate'), ('Matric', 'Matric'), ('Other', 'Other')], max_length=20)),
                ('last_degree', models.CharField(blank=True, max_length=100)),
                ('session_pref', models.CharField(choices=[('Online', 'Online'), ('Onsite', 'Onsite')], max_length=10)),
                ('registered_courses', models.ManyToManyField(to='core.course')),
            ],
        ),
    ]
