# Generated by Django 5.0.6 on 2025-07-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default=4, max_length=128),
            preserve_default=False,
        ),
    ]
